### ISSUE TITLE
Can't get the bot to speak in channel (Error status code 400)

### ISSUE THREAD

**Issue by cash-bonus** [moonstar-x/discord-tts-bot#31]
#### :confused: Question

> I'm self hosting the bot, the bot is in the server and will join voice channels, but will not say anything with $say or $aeiou

#### :question: Additional Information

> I already have ffmpeg installed and updated

![image](https://user-images.githubusercontent.com/68239191/104363190-d81c2f80-54e2-11eb-9eeb-755f1a163e9a.png)

**Comment by moonstar-x** [comment]
Hey there, are you hosting this on your own machine or in a VPS/Heroku-like service?

**Comment by cash-bonus** [comment]
Im hosting on my own raspberry pi

**Comment by cash-bonus** [comment]
It actually works for a minute now after i reinstall

**Comment by cash-bonus** [comment]
but when my friend tried it it started giving errors again

**Comment by cash-bonus** [comment]
for some strange reason if I stop the bot on my raspberry pi, re run the npm install command, and turn it back on it will start working again? The problem seems to happen when more than one person, or the same person on a different server, try to call the bot.

**Comment by moonstar-x** [comment]
Hmm, this is kinda weird. I can only assume it's got something to do with discord.js, in what country do you live? What happens if you go to [this site](http://tts.cyzon.us/tts?text=this%20is%20a%20test)?

**Comment by moonstar-x** [comment]
Oh wait hold on, by any chance, the text channel where you're trying to do the commands `say` or `aeiou`, does the bot have enough permissions to send messages?

Does the bot send a message saying "Joined (channel name)" in the text channel that you used to summon it?

**Comment by cash-bonus** [comment]
the bot does send messages

**Comment by cash-bonus** [comment]
i live in usa

**Comment by moonstar-x** [comment]
Kinda weird, the error sounds like it's coming from the message send since the bot doesn't log "received TTS for..." which means that it never got there in the first place, and since the error messages are exactly the same for aeiou and say, I imagine it would be due to the message sending failing but then again the error log would begin with DiscordAPIError normally.

I have a raspberry pi lying around, let me try running the bot from there.

**Comment by moonstar-x** [comment]
![image](https://user-images.githubusercontent.com/14969195/104383650-2a1e7e80-54fe-11eb-8791-d5e0e4ac74ea.png)

I have no clue what could be causing this. Only thing I can imagine is that you may be having troubles in your own network or your raspberry pi has trouble accessing the required resources.

I tried running the bot from a raspberry pi, on two different servers and I can't get the error you're getting.

**Comment by cash-bonus** [comment]
Ah ok. I do have a seedbox running on the same pi so maybe it is a resource issue.

**Comment by moonstar-x** [comment]
Hmm, I'm not 100% sure about that. Maybe try waiting a bit then trying again?

Quite unfortunately I can't reproduce this issue on my own raspberry pi so I'm assuming it must be due to something on your setup/connection.

Sorry I can't help you any further. If you prefer, you can use the instance I'm hosting from my own server (invite link is in README).
