### ISSUE TITLE
Can you add alliances for say  

### ISSUE THREAD

**Issue by ChandanGaming** [moonstar-x/discord-tts-bot#37]
Sometimes it is hard to write prefix and say then the text .
just add alliances for say like ( $s [text] )

**Comment by moonstar-x** [comment]
Added in #39.

Please update your bot by pulling the changes:

```text
git pull origin master
```

And reinstalling the dependencies:

```text
rm -rf node_modules
npm ci --only=prod
```

Keep in mind that this is a breaking update, which means that certain things may break, especially with the bot's configuration since I've added new configs but also renamed the ones for the token. For more information, check out [this neat table](https://github.com/moonstar-x/discord-tts-bot/tree/v3.0.0#configuration) showing all the new bot's configuration.
