### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Walker79** [moonstar-x/discord-tts-bot#48]
code is not working and your official bot too ;-;

**Comment by moonstar-x** [comment]
Could you please be a bit more specific?

I'm currently seeing people using my instance of the bot with no problem.

What issue are you running into?

**Comment by Walker79** [comment]
bot joins vc but dont say anything ;-;

**Comment by moonstar-x** [comment]
Is your server name perhaps `Bada Bing!`?

If so, the console is saying your bot does not have enough permissions to talk in the channel.

**Comment by Walker79** [comment]
thank you i m so dumb ;-;

**Comment by moonstar-x** [comment]
Don't worry and thank you for the issue. This is technically a bug because the bot should be able to tell you that the channel does not have enough permissions anyways and I do believe it doesn't say anything. 
Someone already made a PR regarding this #44 and I'm just waiting for them to make some changes to be able to merge.
