### ISSUE TITLE
Crash on Leaving ${channel.name} do to inactivity

### ISSUE THREAD

**Issue by TheCrafters001** [moonstar-x/discord-tts-bot#64]
#### :bug: Describe the Bug

Bot crashes when trying to send a log message out for leaving due to inactivity

#### :pencil2: Steps to Reproduce

> 1. Turn bot on, and say a message
> 2. Do not send any other message for the duration of your inactivity timer
> 3. The bot will crash.

#### :confused: Expected Behavior

Expected bot to leave without crashing.

#### :scroll: Log

``` text
C:\PathName\discord-tts-bot\src\classes\tts\TTSPlayer.js:44
      logger.warn(`Left ${channel.name} from ${this.guild.name} due to inactivity.`);
                                  ^

TypeError: Cannot read properties of null (reading 'name')
    at Scheduler.fn (D:\My Files\Desktop\Software Stuff\Software\Github\discord-tts-bot\src\classes\tts\TTSPlayer.js:44:35)
    at Timeout.<anonymous> (D:\My Files\Desktop\Software Stuff\Software\Github\discord-tts-bot\src\classes\Scheduler.js:21:12)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

[process exited with code 1] (Ignore this, it's a windows terminal thing.)
```

#### :camera: Screenshots

![image](https://user-images.githubusercontent.com/46639269/150913070-9de1251b-c919-4332-b8b7-e410e8c813d7.png)

#### :question: Other Information

* Node Version: `v16.13.2`

**Comment by moonstar-x** [comment]
Hey there, what version of the bot are you using?

**Comment by TheCrafters001** [comment]
Hey, sorry, forgot to include that.
I know I fell behind a couple of versions, but I am on 4.0.2.

**Comment by moonstar-x** [comment]
Yeah this is a bug that is supposed to be fixed in the lastest one. If you can update to 4.0.4 it should work.

Tell me how it goes after you update. You can check [this](https://github.com/moonstar-x/discord-tts-bot#updating) for more info on how to updating. (Updating the dependencies is kinda important because some of the bugs that have been fixed for this came from the framework that I maintain and use for this).
